window.gameData = window.gameData || {};
window.gameData.countries = [
    // South America
    { name: "Argentina", code: "ar", continent: "South America", capital: "Buenos Aires", cities: ["Córdoba", "Rosario", "Mendoza", "La Plata", "San Miguel de Tucumán", "Buenos Aires"] },
    { name: "Bolivia", code: "bo", continent: "South America", capital: "Sucre", cities: ["La Paz", "Cochabamba", "Santa Cruz de la Sierra", "Oruro", "Potosí", "Sucre"] },
    { name: "Brazil", code: "br", continent: "South America", capital: "Brasília", cities: ["São Paulo", "Rio de Janeiro", "Salvador", "Fortaleza", "Belo Horizonte", "Brasília"] },
    { name: "Chile", code: "cl", continent: "South America", capital: "Santiago", cities: ["Valparaíso", "Concepción", "La Serena", "Antofagasta", "Temuco", "Santiago"] },
    { name: "Colombia", code: "co", continent: "South America", capital: "Bogotá", cities: ["Medellín", "Cali", "Barranquilla", "Cartagena", "Cúcuta", "Bogotá"] },
    { name: "Ecuador", code: "ec", continent: "South America", capital: "Quito", cities: ["Guayaquil", "Cuenca", "Santo Domingo", "Machala", "Manta", "Quito"] },
    { name: "Guyana", code: "gy", continent: "South America", capital: "Georgetown", cities: ["Linden", "New Amsterdam", "Anna Regina", "Bartica", "Skeldon", "Georgetown"] },
    { name: "Paraguay", code: "py", continent: "South America", capital: "Asunción", cities: ["Ciudad del Este", "San Lorenzo", "Luque", "Capiatá", "Lambaré", "Asunción"] },
    { name: "Peru", code: "pe", continent: "South America", capital: "Lima", cities: ["Arequipa", "Trujillo", "Chiclayo", "Piura", "Cusco", "Lima"] },
    { name: "Suriname", code: "sr", continent: "South America", capital: "Paramaribo", cities: ["Lelydorp", "Nieuw Nickerie", "Moengo", "Wageningen", "Albina", "Paramaribo"] },
    { name: "Uruguay", code: "uy", continent: "South America", capital: "Montevideo", cities: ["Salto", "Ciudad de la Costa", "Paysandú", "Las Piedras", "Rivera", "Montevideo"] },
    { name: "Venezuela", code: "ve", continent: "South America", capital: "Caracas", cities: ["Maracaibo", "Valencia", "Barquisimeto", "Maracay", "Ciudad Guayana", "Caracas"] },

    // North America (includes Central and Caribbean)
    { name: "United States", code: "us", continent: "North America", capital: "Washington, D.C.", cities: ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Washington, D.C."] },
    { name: "Canada", code: "ca", continent: "North America", capital: "Ottawa", cities: ["Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton", "Ottawa"] },
    { name: "Mexico", code: "mx", continent: "North America", capital: "Mexico City", cities: ["Guadalajara", "Monterrey", "Puebla", "Tijuana", "Cancún", "Mexico City"] },
    { name: "Antigua and Barbuda", code: "ag", continent: "North America", capital: "St. John's", cities: ["All Saints", "Liberta", "Potters Village", "Bolans", "Swetes", "St. John's"] },
    { name: "Bahamas", code: "bs", continent: "North America", capital: "Nassau", cities: ["Freeport", "West End", "Coopers Town", "Marsh Harbour", "Freetown", "Nassau"] },
    { name: "Barbados", code: "bb", continent: "North America", capital: "Bridgetown", cities: ["Speightstown", "Oistins", "Bathsheba", "Holetown", "Crane", "Bridgetown"] },
    { name: "Belize", code: "bz", continent: "North America", capital: "Belmopan", cities: ["Belize City", "San Ignacio", "Orange Walk Town", "Dangriga", "Corozal Town", "Belmopan"] },
    { name: "Costa Rica", code: "cr", continent: "North America", capital: "San José", cities: ["Alajuela", "Cartago", "Heredia", "Liberia", "Puntarenas", "San José"] },
    { name: "Cuba", code: "cu", continent: "North America", capital: "Havana", cities: ["Santiago de Cuba", "Camagüey", "Holguín", "Santa Clara", "Guantánamo", "Havana"] },
    { name: "Dominica", code: "dm", continent: "North America", capital: "Roseau", cities: ["Portsmouth", "Marigot", "Berekua", "Mahaut", "Saint Joseph", "Roseau"] },
    { name: "Dominican Republic", code: "do", continent: "North America", capital: "Santo Domingo", cities: ["Santiago de los Caballeros", "Santo Domingo Este", "Santo Domingo Oeste", "Santo Domingo Norte", "La Vega", "Santo Domingo"] },
    { name: "El Salvador", code: "sv", continent: "North America", capital: "San Salvador", cities: ["Soyapango", "Santa Ana", "San Miguel", "Mejicanos", "Apopa", "San Salvador"] },
    { name: "Grenada", code: "gd", continent: "North America", capital: "St. George's", cities: ["Gouyave", "Grenville", "Victoria", "Saint David's", "Sauteurs", "St. George's"] },
    { name: "Guatemala", code: "gt", continent: "North America", capital: "Guatemala City", cities: ["Mixco", "Villa Nueva", "Quetzaltenango", "San Miguel Petapa", "Escuintla", "Guatemala City"] },
    { name: "Haiti", code: "ht", continent: "North America", capital: "Port-au-Prince", cities: ["Carrefour", "Delmas", "Pétion-Ville", "Cité Soleil", "Gonaïves", "Port-au-Prince"] },
    { name: "Honduras", code: "hn", continent: "North America", capital: "Tegucigalpa", cities: ["San Pedro Sula", "Choloma", "La Ceiba", "El Progreso", "Choluteca", "Tegucigalpa"] },
    { name: "Jamaica", code: "jm", continent: "North America", capital: "Kingston", cities: ["Portmore", "Spanish Town", "Montego Bay", "May Pen", "Mandeville", "Kingston"] },
    { name: "Nicaragua", code: "ni", continent: "North America", capital: "Managua", cities: ["León", "Masaya", "Matagalpa", "Tipitapa", "Chinandega", "Managua"] },
    { name: "Panama", code: "pa", continent: "North America", capital: "Panama City", cities: ["San Miguelito", "Tocumen", "David", "Arraiján", "Colón", "Panama City"] },
    { name: "Saint Kitts and Nevis", code: "kn", continent: "North America", capital: "Basseterre", cities: ["Charlestown", "Sadlers", "Cayon", "Sandy Point Town", "Dieppe Bay Town", "Basseterre"] },
    { name: "Saint Lucia", code: "lc", continent: "North America", capital: "Castries", cities: ["Gros Islet", "Vieux Fort", "Micoud", "Dennery", "Soufrière", "Castries"] },
    { name: "Saint Vincent and the Grenadines", code: "vc", continent: "North America", capital: "Kingstown", cities: ["Georgetown", "Byera Village", "Biabou", "Port Elizabeth", "Chateaubelair", "Kingstown"] },
    { name: "Trinidad and Tobago", code: "tt", continent: "North America", capital: "Port of Spain", cities: ["Chaguanas", "San Fernando", "Arima", "Point Fortin", "Couva", "Port of Spain"] },

    // Europe
    { name: "Albania", code: "al", continent: "Europe", capital: "Tirana", cities: ["Durrës", "Vlorë", "Shkodër", "Fier", "Korçë", "Tirana"] },
    { name: "Andorra", code: "ad", continent: "Europe", capital: "Andorra la Vella", cities: ["Escaldes-Engordany", "Encamp", "Sant Julià de Lòria", "La Massana", "Canillo", "Andorra la Vella"] },
    { name: "Armenia", code: "am", continent: "Europe", capital: "Yerevan", cities: ["Gyumri", "Vanadzor", "Vagharshapat", "Abovyan", "Kapan", "Yerevan"] },
    { name: "Austria", code: "at", continent: "Europe", capital: "Vienna", cities: ["Graz", "Linz", "Salzburg", "Innsbruck", "Kagenfurt", "Vienna"] },
    { name: "Belarus", code: "by", continent: "Europe", capital: "Minsk", cities: ["Gomel", "Mogilev", "Vitebsk", "Grodno", "Brest", "Minsk"] },
    { name: "Belgium", code: "be", continent: "Europe", capital: "Brussels", cities: ["Antwerp", "Ghent", "Charleroi", "Liège", "Bruges", "Brussels"] },
    { name: "Bosnia and Herzegovina", code: "ba", continent: "Europe", capital: "Sarajevo", cities: ["Banja Luka", "Tuzla", "Zenica", "Mostar", "Bijeljina", "Sarajevo"] },
    { name: "Bulgaria", code: "bg", continent: "Europe", capital: "Sofia", cities: ["Plovdiv", "Varna", "Burgas", "Ruse", "Stara Zagora", "Sofia"] },
    { name: "Croatia", code: "hr", continent: "Europe", capital: "Zagreb", cities: ["Split", "Rijeka", "Dubrovnik", "Zadar", "Pula", "Zagreb"] },
    { name: "Cyprus", code: "cy", continent: "Europe", capital: "Nicosia", cities: ["Limassol", "Larnaca", "Famagusta", "Paphos", "Kyrenia", "Nicosia"] },
    { name: "Czech Republic", code: "cz", continent: "Europe", capital: "Prague", cities: ["Brno", "Ostrava", "Plzeň", "Liberec", "Olomouc", "Prague"] },
    { name: "Denmark", code: "dk", continent: "Europe", capital: "Copenhagen", cities: ["Aarhus", "Odense", "Aalborg", "Frederiksberg", "Esbjerg", "Copenhagen"] },
    { name: "Estonia", code: "ee", continent: "Europe", capital: "Tallinn", cities: ["Tartu", "Narva", "Riga", "Vilnius", "Viljandi", "Tallinn"] },
    { name: "Finland", code: "fi", continent: "Europe", capital: "Helsinki", cities: ["Espoo", "Tampere", "Vantaa", "Oulu", "Turku", "Helsinki"] },
    { name: "France", code: "fr", continent: "Europe", capital: "Paris", cities: ["Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Paris"] },
    { name: "Georgia", code: "ge", continent: "Europe", capital: "Tbilisi", cities: ["Batumi", "Kutaisi", "Rustavi", "Gori", "Zugdidi", "Tbilisi"] },
    { name: "Germany", code: "de", continent: "Europe", capital: "Berlin", cities: ["Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart", "Berlin"] },
    { name: "Greece", code: "gr", continent: "Europe", capital: "Athens", cities: ["Thessaloniki", "Patras", "Heraklion", "Ioannina", "Larissa", "Athens"] },
    { name: "Hungary", code: "hu", continent: "Europe", capital: "Budapest", cities: ["Debrecen", "Szeged", "Miskolc", "Pécs", "Győr", "Budapest"] },
    { name: "Iceland", code: "is", continent: "Europe", capital: "Reykjavík", cities: ["Kópavogur", "Hafnarfjörður", "Akureyri", "Reykjanesbær", "Garðabær", "Reykjavík"] },
    { name: "Ireland", code: "ie", continent: "Europe", capital: "Dublin", cities: ["Cork", "Limerick", "Galway", "Waterford", "Drogheda", "Dublin"] },
    { name: "Italy", code: "it", continent: "Europe", capital: "Rome", cities: ["Milan", "Naples", "Turin", "Palermo", "Genoa", "Rome"] },
    { name: "Kosovo", code: "xk", continent: "Europe", capital: "Pristina", cities: ["Prizren", "Ferizaj", "Peja", "Gjakova", "Gjilan", "Pristina"] },
    { name: "Latvia", code: "lv", continent: "Europe", capital: "Riga", cities: ["Vilnius", "Liepāja", "Jelgava", "Jūrmala", "Tallinn", "Riga"] },
    { name: "Liechtenstein", code: "li", continent: "Europe", capital: "Vaduz", cities: ["Schaan", "Triesen", "Balzers", "Eschen", "Mauren", "Vaduz"] },
    { name: "Lithuania", code: "lt", continent: "Europe", capital: "Vilnius", cities: ["Kaunas", "Riga", "Šiauliai", "Tallinn", "Alytus", "Vilnius"] },
    { name: "Luxembourg", code: "lu", continent: "Europe", capital: "Luxembourg City", cities: ["Esch-sur-Alzette", "Dudelange", "Schifflange", "Bettembourg", "Pétange", "Luxembourg City"] },
    { name: "Malta", code: "mt", continent: "Europe", capital: "Valletta", cities: ["Birkirkara", "Qormi", "Mosta", "Żabbar", "San Pawl il-Baħar", "Valletta"] },
    { name: "Moldova", code: "md", continent: "Europe", capital: "Chișinău", cities: ["Bălți", "Tiraspol", "Bender", "Rîbnița", "Cahul", "Chișinău"] },
    { name: "Monaco", code: "mc", continent: "Europe", capital: "Monaco", cities: ["Monte Carlo", "La Condamine", "Fontvieille", "Moneghetti", "Saint Roman", "Monaco"] },
    { name: "Montenegro", code: "me", continent: "Europe", capital: "Podgorica", cities: ["Nikšić", "Herceg Novi", "Pljevlja", "Bar", "Budva", "Podgorica"] },
    { name: "Netherlands", code: "nl", continent: "Europe", capital: "Amsterdam", cities: ["Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Tilburg", "Amsterdam"] },
    { name: "North Macedonia", code: "mk", continent: "Europe", capital: "Skopje", cities: ["Bitola", "Kumanovo", "Prilep", "Tetovo", "Veles", "Skopje"] },
    { name: "Norway", code: "no", continent: "Europe", capital: "Oslo", cities: ["Bergen", "Trondheim", "Copenhagen", "Bærum", "Stockholm", "Oslo"] },
    { name: "Poland", code: "pl", continent: "Europe", capital: "Warsaw", cities: ["Kraków", "Łódź", "Wrocław", "Poznań", "Gdańsk", "Warsaw"] },
    { name: "Portugal", code: "pt", continent: "Europe", capital: "Lisbon", cities: ["Porto", "Vila Nova de Gaia", "Amadora", "Braga", "Funchal", "Lisbon"] },
    { name: "Romania", code: "ro", continent: "Europe", capital: "Bucharest", cities: ["Cluj-Napoca", "Timișoara", "Iași", "Constanța", "Craiova", "Bucharest"] },
    { name: "Russia", code: "ru", continent: "Europe", capital: "Moscow", cities: ["Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan", "Nizhny Novgorod", "Moscow"] },
    { name: "San Marino", code: "sm", continent: "Europe", capital: "San Marino", cities: ["Serravalle", "Borgo Maggiore", "Domagnano", "Fiorentino", "Acquaviva", "San Marino"] },
    { name: "Serbia", code: "rs", continent: "Europe", capital: "Belgrade", cities: ["Novi Sad", "Niš", "Kragujevac", "Subotica", "Pančevo", "Belgrade"] },
    { name: "Slovakia", code: "sk", continent: "Europe", capital: "Bratislava", cities: ["Košice", "Prešov", "Žilina", "Banská Bystrica", "Nitra", "Bratislava"] },
    { name: "Slovenia", code: "si", continent: "Europe", capital: "Ljubljana", cities: ["Maribor", "Celje", "Kranj", "Velenje", "Koper", "Ljubljana"] },
    { name: "Spain", code: "es", continent: "Europe", capital: "Madrid", cities: ["Barcelona", "Valencia", "Seville", "Zaragoza", "Málaga", "Madrid"] },
    { name: "Sweden", code: "se", continent: "Europe", capital: "Stockholm", cities: ["Gothenburg", "Malmö", "Olso", "Copenhagen", "Örebro", "Stockholm"] },
    { name: "Switzerland", code: "ch", continent: "Europe", capital: "Bern", cities: ["Zurich", "Geneva", "Basel", "Lausanne", "Lucerne", "Bern"] },
    { name: "Ukraine", code: "ua", continent: "Europe", capital: "Kyiv", cities: ["Kharkiv", "Odesa", "Dnipro", "Donetsk", "Zaporizhzhia", "Kyiv"] },
    { name: "United Kingdom", code: "gb", continent: "Europe", capital: "London", cities: ["Manchester", "Birmingham", "Liverpool", "Glasgow", "Edinburgh", "London"] },
    { name: "Vatican City", code: "va", continent: "Europe", capital: "Vatican City", cities: ["Vatican City", "Rome", "Prati", "Borgo", "Trastevere", "Vatican City"] },

    // Asia
    { name: "Afghanistan", code: "af", continent: "Asia", capital: "Kabul", cities: ["Kandahar", "Herat", "Mazar-i-Sharif", "Jalalabad", "Kunduz", "Kabul"] },
    { name: "Azerbaijan", code: "az", continent: "Asia", capital: "Baku", cities: ["Ganja", "Sumqayit", "Mingachevir", "Shirvan", "Nakhchivan", "Baku"] },
    { name: "Bahrain", code: "bh", continent: "Asia", capital: "Manama", cities: ["Riffa", "Muharraq", "Hamad Town", "A'ali", "Sitra", "Manama"] },
    { name: "Bangladesh", code: "bd", continent: "Asia", capital: "Dhaka", cities: ["Chittagong", "Khulna", "Rajshahi", "Sylhet", "Barisal", "Dhaka"] },
    { name: "Bhutan", code: "bt", continent: "Asia", capital: "Thimphu", cities: ["Phuntsholing", "Paro", "Gelephu", "Samdrup Jongkhar", "Wangdue Phodrang", "Thimphu"] },
    { name: "Brunei", code: "bn", continent: "Asia", capital: "Bandar Seri Begawan", cities: ["Kuala Belait", "Seria", "Tutong", "Bangar", "Muara", "Bandar Seri Begawan"] },
    { name: "Cambodia", code: "kh", continent: "Asia", capital: "Phnom Penh", cities: ["Siem Reap", "Battambang", "Sihanoukville", "Kampot", "Kampong Cham", "Phnom Penh"] },
    { name: "China", code: "cn", continent: "Asia", capital: "Beijing", cities: ["Shanghai", "Guangzhou", "Shenzhen", "Chengdu", "Wuhan", "Beijing"] },
    { name: "Timor-Leste", code: "tl", continent: "Asia", capital: "Dili", cities: ["Baucau", "Maliana", "Suai", "Lospalos", "Same", "Dili"] },
    { name: "India", code: "in", continent: "Asia", capital: "New Delhi", cities: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "New Delhi"] },
    { name: "Indonesia", code: "id", continent: "Asia", capital: "Jakarta", cities: ["Surabaya", "Bandung", "Medan", "Semarang", "Palembang", "Jakarta"] },
    { name: "Iran", code: "ir", continent: "Asia", capital: "Tehran", cities: ["Mashhad", "Isfahan", "Karaj", "Shiraz", "Tabriz", "Tehran"] },
    { name: "Iraq", code: "iq", continent: "Asia", capital: "Baghdad", cities: ["Basra", "Mosul", "Erbil", "Kirkuk", "Najaf", "Baghdad"] },
    { name: "Israel", code: "il", continent: "Asia", capital: "Jerusalem", cities: ["Tel Aviv", "Haifa", "Rishon LeZion", "Petah Tikva", "Ashdod", "Jerusalem"] },
    { name: "Japan", code: "jp", continent: "Asia", capital: "Tokyo", cities: ["Yokohama", "Osaka", "Nagoya", "Sapporo", "Fukuoka", "Tokyo"] },
    { name: "Jordan", code: "jo", continent: "Asia", capital: "Amman", cities: ["Zarqa", "Irbid", "Russeifa", "Aqaba", "Salt", "Amman"] },
    { name: "Kazakhstan", code: "kz", continent: "Asia", capital: "Astana", cities: ["Almaty", "Shymkent", "Karaganda", "Aktobe", "Taraz", "Astana"] },
    { name: "Kuwait", code: "kw", continent: "Asia", capital: "Kuwait City", cities: ["Hawalli", "Salmiya", "Farwaniya", "Jahra", "Ahmadi", "Kuwait City"] },
    { name: "Kyrgyzstan", code: "kg", continent: "Asia", capital: "Bishkek", cities: ["Osh", "Jalal-Abad", "Karakol", "Tokmok", "Kara-Balta", "Bishkek"] },
    { name: "Laos", code: "la", continent: "Asia", capital: "Vientiane", cities: ["Pakse", "Savannakhet", "Luang Prabang", "Xam Neua", "Phonsavan", "Vientiane"] },
    { name: "Lebanon", code: "lb", continent: "Asia", capital: "Beirut", cities: ["Tripoli", "Sidon", "Tyre", "Jounieh", "Zahle", "Beirut"] },
    { name: "Malaysia", code: "my", continent: "Asia", capital: "Kuala Lumpur", cities: ["George Town", "Johor Bahru", "Ipoh", "Shah Alam", "Petaling Jaya", "Kuala Lumpur"] },
    { name: "Maldives", code: "mv", continent: "Asia", capital: "Malé", cities: ["Addu City", "Fuvahmulah", "Kulhudhuffushi", "Thinadhoo", "Naifaru", "Malé"] },
    { name: "Mongolia", code: "mn", continent: "Asia", capital: "Ulaanbaatar", cities: ["Erdenet", "Darkhan", "Choibalsan", "Mörön", "Nalaikh", "Ulaanbaatar"] },
    { name: "Myanmar", code: "mm", continent: "Asia", capital: "Naypyidaw", cities: ["Yangon", "Mandalay", "Mawlamyine", "Bago", "Pathein", "Naypyidaw"] },
    { name: "Nepal", code: "np", continent: "Asia", capital: "Kathmandu", cities: ["Pokhara", "Lalitpur", "Bharatpur", "Biratnagar", "Birgunj", "Kathmandu"] },
    { name: "North Korea", code: "kp", continent: "Asia", capital: "Pyongyang", cities: ["Hamhung", "Chongjin", "Nampo", "Wonsan", "Sinuiju", "Pyongyang"] },
    { name: "Oman", code: "om", continent: "Asia", capital: "Muscat", cities: ["Salalah", "Sohar", "Nizwa", "Sur", "Buraimi", "Muscat"] },
    { name: "Pakistan", code: "pk", continent: "Asia", capital: "Islamabad", cities: ["Karachi", "Lahore", "Faisalabad", "Rawalpindi", "Multan", "Islamabad"] },
    { name: "Palestine", code: "ps", continent: "Asia", capital: "Ramallah", cities: ["Gaza City", "Hebron", "Nablus", "Khan Yunis", "Jenin", "Ramallah"] },
    { name: "Philippines", code: "ph", continent: "Asia", capital: "Manila", cities: ["Quezon City", "Davao City", "Cebu City", "Zamboanga City", "Taguig", "Manila"] },
    { name: "Qatar", code: "qa", continent: "Asia", capital: "Doha", cities: ["Al Rayyan", "Al Wakrah", "Al Khor", "Umm Salal", "Al Daayen", "Doha"] },
    { name: "Saudi Arabia", code: "sa", continent: "Asia", capital: "Riyadh", cities: ["Jeddah", "Mecca", "Medina", "Dammam", "Taif", "Riyadh"] },
    { name: "Singapore", code: "sg", continent: "Asia", capital: "Singapore", cities: ["Jurong East", "Woodlands", "Tampines", "Pasir Ris", "Yishun", "Singapore"] },
    { name: "South Korea", code: "kr", continent: "Asia", capital: "Seoul", cities: ["Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Seoul"] },
    { name: "Sri Lanka", code: "lk", continent: "Asia", capital: "Sri Jayawardenepura Kotte", cities: ["Colombo", "Kandy", "Galle", "Jaffna", "Negombo", "Sri Jayawardenepura Kotte"] },
    { name: "Syria", code: "sy", continent: "Asia", capital: "Damascus", cities: ["Aleppo", "Homs", "Hama", "Latakia", "Tartus", "Damascus"] },
    { name: "Taiwan", code: "tw", continent: "Asia", capital: "Taipei", cities: ["New Taipei", "Kaohsiung", "Taichung", "Tainan", "Taoyuan", "Taipei"] },
    { name: "Tajikistan", code: "tj", continent: "Asia", capital: "Dushanbe", cities: ["Khujand", "Kulob", "Bokhtar", "Istaravshan", "Tursunzoda", "Dushanbe"] },
    { name: "Thailand", code: "th", continent: "Asia", capital: "Bangkok", cities: ["Chiang Mai", "Phuket", "Pattaya", "Krabi", "Hat Yai", "Bangkok"] },
    { name: "Turkey", code: "tr", continent: "Asia", capital: "Ankara", cities: ["Istanbul", "Izmir", "Bursa", "Adana", "Gaziantep", "Ankara"] },
    { name: "Turkmenistan", code: "tm", continent: "Asia", capital: "Ashgabat", cities: ["Türkmenabat", "Daşoguz", "Mary", "Balkanabat", "Bayramaly", "Ashgabat"] },
    { name: "United Arab Emirates", code: "ae", continent: "Asia", capital: "Abu Dhabi", cities: ["Dubai", "Sharjah", "Al Ain", "Ajman", "Ras Al Khaimah", "Abu Dhabi"] },
    { name: "Uzbekistan", code: "uz", continent: "Asia", capital: "Tashkent", cities: ["Samarkand", "Namangan", "Andijan", "Nukus", "Bukhara", "Tashkent"] },
    { name: "Vietnam", code: "vn", continent: "Asia", capital: "Hanoi", cities: ["Ho Chi Minh City", "Da Nang", "Hai Phong", "Can Tho", "Bien Hoa", "Hanoi"] },
    { name: "Yemen", code: "ye", continent: "Asia", capital: "Sanaa", cities: ["Aden", "Taiz", "Hodeidah", "Mukalla", "Ibb", "Sanaa"] },

    // Africa
    { name: "Algeria", code: "dz", continent: "Africa", capital: "Algiers", cities: ["Oran", "Constantine", "Annaba", "Blida", "Batna", "Algiers"] },
    { name: "Angola", code: "ao", continent: "Africa", capital: "Luanda", cities: ["Huambo", "Lobito", "Benguela", "Lubango", "Malanje", "Luanda"] },
    { name: "Benin", code: "bj", continent: "Africa", capital: "Porto-Novo", cities: ["Cotonou", "Parakou", "Djougou", "Bohicon", "Kandi", "Porto-Novo"] },
    { name: "Botswana", code: "bw", continent: "Africa", capital: "Gaborone", cities: ["Francistown", "Molepolole", "Maun", "Serowe", "Selibe Phikwe", "Gaborone"] },
    { name: "Burkina Faso", code: "bf", continent: "Africa", capital: "Ouagadougou", cities: ["Bobo-Dioulasso", "Koudougou", "Banfora", "Ouahigouya", "Kaya", "Ouagadougou"] },
    { name: "Burundi", code: "bi", continent: "Africa", capital: "Gitega", cities: ["Bujumbura", "Muyinga", "Ngozi", "Ruyigi", "Kayanza", "Gitega"] },
    { name: "Cameroon", code: "cm", continent: "Africa", capital: "Yaoundé", cities: ["Douala", "Bamenda", "Bafoussam", "Garoua", "Maroua", "Yaoundé"] },
    { name: "Cape Verde", code: "cv", continent: "Africa", capital: "Praia", cities: ["Mindelo", "Santa Maria", "Assomada", "Tarrafal", "Espargos", "Praia"] },
    { name: "Central African Republic", code: "cf", continent: "Africa", capital: "Bangui", cities: ["Bimbo", "Berbérati", "Carnot", "Bambari", "Bouar", "Bangui"] },
    { name: "Chad", code: "td", continent: "Africa", capital: "N'Djamena", cities: ["Moundou", "Sarh", "Abéché", "Kélo", "Koumra", "N'Djamena"] },
    { name: "Comoros", code: "km", continent: "Africa", capital: "Moroni", cities: ["Mutsamudu", "Fomboni", "Domoni", "Mirontsi", "Ouani", "Moroni"] },
    { name: "Democratic Republic of the Congo", code: "cd", continent: "Africa", capital: "Kinshasa", cities: ["Lubumbashi", "Mbuji-Mayi", "Kananga", "Kisangani", "Bukavu", "Kinshasa"] },
    { name: "Republic of the Congo", code: "cg", continent: "Africa", capital: "Brazzaville", cities: ["Pointe-Noire", "Dolisie", "Nkayi", "Impfondo", "Ouesso", "Brazzaville"] },
    { name: "Djibouti", code: "dj", continent: "Africa", capital: "Djibouti City", cities: ["Ali Sabieh", "Tadjoura", "Obock", "Dikhil", "Arta", "Djibouti City"] },
    { name: "Egypt", code: "eg", continent: "Africa", capital: "Cairo", cities: ["Alexandria", "Giza", "Shubra El-Kheima", "Port Said", "Suez", "Cairo"] },
    { name: "Equatorial Guinea", code: "gq", continent: "Africa", capital: "Malabo", cities: ["Bata", "Ebebiyín", "Mongomo", "Añisoc", "Luba", "Malabo"] },
    { name: "Eritrea", code: "er", continent: "Africa", capital: "Asmara", cities: ["Keren", "Massawa", "Assab", "Mendefera", "Barentu", "Asmara"] },
    { name: "Eswatini", code: "sz", continent: "Africa", capital: "Mbabane", cities: ["Manzini", "Big Bend", "Malkerns", "Nhlangano", "Siteki", "Mbabane"] },
    { name: "Ethiopia", code: "et", continent: "Africa", capital: "Addis Ababa", cities: ["Dire Dawa", "Mek'ele", "Gondar", "Adama", "Hawassa", "Addis Ababa"] },
    { name: "Gabon", code: "ga", continent: "Africa", capital: "Libreville", cities: ["Port-Gentil", "Franceville", "Oyem", "Moanda", "Mouila", "Libreville"] },
    { name: "Gambia", code: "gm", continent: "Africa", capital: "Banjul", cities: ["Serekunda", "Brikama", "Bakau", "Farafenni", "Lamin", "Banjul"] },
    { name: "Ghana", code: "gh", continent: "Africa", capital: "Accra", cities: ["Kumasi", "Tamale", "Takoradi", "Achimota", "Tema", "Accra"] },
    { name: "Guinea", code: "gn", continent: "Africa", capital: "Conakry", cities: ["Nzérékoré", "Kankan", "Kindia", "Siguiri", "Boké", "Conakry"] },
    { name: "Guinea-Bissau", code: "gw", continent: "Africa", capital: "Bissau", cities: ["Bafatá", "Gabú", "Bissorã", "Bolama", "Cacheu", "Bissau"] },
    { name: "Ivory Coast", code: "ci", continent: "Africa", capital: "Yamoussoukro", cities: ["Abidjan", "Bouaké", "Daloa", "San-Pédro", "Korhogo", "Yamoussoukro"] },
    { name: "Kenya", code: "ke", continent: "Africa", capital: "Nairobi", cities: ["Mombasa", "Kisumu", "Nakuru", "Eldoret", "Malindi", "Nairobi"] },
    { name: "Lesotho", code: "ls", continent: "Africa", capital: "Maseru", cities: ["Teyateyaneng", "Mafeteng", "Hlotse", "Mohale's Hoek", "Maputsoe", "Maseru"] },
    { name: "Liberia", code: "lr", continent: "Africa", capital: "Monrovia", cities: ["Gbarnga", "Buchanan", "Ganta", "Kakata", "Voinjama", "Monrovia"] },
    { name: "Libya", code: "ly", continent: "Africa", capital: "Tripoli", cities: ["Benghazi", "Misrata", "Bayda", "Zawiya", "Tobruk", "Tripoli"] },
    { name: "Madagascar", code: "mg", continent: "Africa", capital: "Antananarivo", cities: ["Toamasina", "Antsirabe", "Fianarantsoa", "Mahajanga", "Toliara", "Antananarivo"] },
    { name: "Malawi", code: "mw", continent: "Africa", capital: "Lilongwe", cities: ["Blantyre", "Mzuzu", "Zomba", "Kasungu", "Mangochi", "Lilongwe"] },
    { name: "Mali", code: "ml", continent: "Africa", capital: "Bamako", cities: ["Sikasso", "Mopti", "Koutiala", "Kayes", "Ségou", "Bamako"] },
    { name: "Mauritania", code: "mr", continent: "Africa", capital: "Nouakchott", cities: ["Nouadhibou", "Kiffa", "Kaédi", "Zouérat", "Rosso", "Nouakchott"] },
    { name: "Mauritius", code: "mu", continent: "Africa", capital: "Port Louis", cities: ["Beau Bassin-Rose Hill", "Vacoas-Phoenix", "Curepipe", "Quatre Bornes", "Triolet", "Port Louis"] },
    { name: "Morocco", code: "ma", continent: "Africa", capital: "Rabat", cities: ["Casablanca", "Fez", "Tangier", "Marrakesh", "Agadir", "Rabat"] },
    { name: "Mozambique", code: "mz", continent: "Africa", capital: "Maputo", cities: ["Matola", "Beira", "Nampula", "Chimoio", "Nacala", "Maputo"] },
    { name: "Namibia", code: "na", continent: "Africa", capital: "Windhoek", cities: ["Rundu", "Walvis Bay", "Swakopmund", "Oshakati", "Rehoboth", "Windhoek"] },
    { name: "Niger", code: "ne", continent: "Africa", capital: "Niamey", cities: ["Zinder", "Maradi", "Agadez", "Tahoua", "Dosso", "Niamey"] },
    { name: "Nigeria", code: "ng", continent: "Africa", capital: "Abuja", cities: ["Lagos", "Kano", "Ibadan", "Kaduna", "Port Harcourt", "Abuja"] },
    { name: "Rwanda", code: "rw", continent: "Africa", capital: "Kigali", cities: ["Butare", "Muhanga", "Ruhengeri", "Gisenyi", "Byumba", "Kigali"] },
    { name: "Sao Tome and Principe", code: "st", continent: "Africa", capital: "São Tomé", cities: ["Trindade", "Santana", "Neves", "Santo Amaro", "Guadalupe", "São Tomé"] },
    { name: "Senegal", code: "sn", continent: "Africa", capital: "Dakar", cities: ["Touba", "Thiès", "Rufisque", "Kaolack", "Saint-Louis", "Dakar"] },
    { name: "Seychelles", code: "sc", continent: "Africa", capital: "Victoria", cities: ["Anse Boileau", "Beau Vallon", "Anse Royale", "Cascade", "Takamaka", "Victoria"] },
    { name: "Sierra Leone", code: "sl", continent: "Africa", capital: "Freetown", cities: ["Bo", "Kenema", "Makeni", "Koidu Town", "Lunsar", "Freetown"] },
    { name: "Somalia", code: "so", continent: "Africa", capital: "Mogadishu", cities: ["Hargeisa", "Bosaso", "Galkayo", "Berbera", "Kismayo", "Mogadishu"] },
    { name: "South Africa", code: "za", continent: "Africa", capital: "Pretoria", cities: ["Johannesburg", "Cape Town", "Durban", "Soweto", "Gqeberha", "Pretoria"] },
    { name: "South Sudan", code: "ss", continent: "Africa", capital: "Juba", cities: ["Wau", "Malakal", "Yei", "Yambio", "Aweil", "Juba"] },
    { name: "Sudan", code: "sd", continent: "Africa", capital: "Khartoum", cities: ["Omdurman", "Nyala", "Port Sudan", "Kassala", "El Obeid", "Khartoum"] },
    { name: "Tanzania", code: "tz", continent: "Africa", capital: "Dodoma", cities: ["Dar es Salaam", "Mwanza", "Arusha", "Mbeya", "Morogoro", "Dodoma"] },
    { name: "Togo", code: "tg", continent: "Africa", capital: "Lomé", cities: ["Sokodé", "Kara", "Kpalimé", "Atakpamé", "Bassar", "Lomé"] },
    { name: "Tunisia", code: "tn", continent: "Africa", capital: "Tunis", cities: ["Sfax", "Sousse", "Ettadhamen", "Kairouan", "Gabès", "Tunis"] },
    { name: "Uganda", code: "ug", continent: "Africa", capital: "Kampala", cities: ["Gulu", "Lira", "Mbarara", "Jinja", "Bwizibwera", "Kampala"] },
    { name: "Zambia", code: "zm", continent: "Africa", capital: "Lusaka", cities: ["Kitwe", "Ndola", "Kabwe", "Chingola", "Mufulira", "Lusaka"] },
    { name: "Zimbabwe", code: "zw", continent: "Africa", capital: "Harare", cities: ["Bulawayo", "Chitungwiza", "Mutare", "Epworth", "Gweru", "Harare"] },

    // Oceania
    { name: "Australia", code: "au", continent: "Oceania", capital: "Canberra", cities: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Canberra"] },
    { name: "Fiji", code: "fj", continent: "Oceania", capital: "Suva", cities: ["Lautoka", "Nadi", "Labasa", "Ba", "Lami", "Suva"] },
    { name: "Kiribati", code: "ki", continent: "Oceania", capital: "South Tarawa", cities: ["Betio", "Bikenibeu", "Teaoraereke", "Bairiki", "Eita", "South Tarawa"] },
    { name: "Marshall Islands", code: "mh", continent: "Oceania", capital: "Majuro", cities: ["Ebeye", "Rita", "Delap", "Uliga", "Rairok", "Majuro"] },
    { name: "Micronesia", code: "fm", continent: "Oceania", capital: "Palikir", cities: ["Weno", "Kolonia", "Tofol", "Colonia", "Lelu", "Palikir"] },
    { name: "Nauru", code: "nr", continent: "Oceania", capital: "Yaren", cities: ["Denigomodu", "Meneng", "Aiwo", "Boe", "Buada", "Yaren"] },
    { name: "New Zealand", code: "nz", continent: "Oceania", capital: "Wellington", cities: ["Auckland", "Christchurch", "Hamilton", "Tauranga", "Napier", "Wellington"] },
    { name: "Palau", code: "pw", continent: "Oceania", capital: "Ngerulmud", cities: ["Koror", "Airai", "Kloulklubed", "Meyuns", "Ngerkeai", "Ngerulmud"] },
    { name: "Papua New Guinea", code: "pg", continent: "Oceania", capital: "Port Moresby", cities: ["Lae", "Arawa", "Mount Hagen", "Madang", "Kokopo", "Port Moresby"] },
    { name: "Samoa", code: "ws", continent: "Oceania", capital: "Apia", cities: ["Vaitele", "Faleasiu", "Vailele", "Leauvaa", "Siusega", "Apia"] },
    { name: "Solomon Islands", code: "sb", continent: "Oceania", capital: "Honiara", cities: ["Gizo", "Auki", "Noro", "Buala", "Tulagi", "Honiara"] },
    { name: "Tonga", code: "to", continent: "Oceania", capital: "Nukuʻalofa", cities: ["Neiafu", "Haveluloto", "Vaini", "Tofoa-Koloa", "Pangai", "Nukuʻalofa"] },
    { name: "Tuvalu", code: "tv", continent: "Oceania", capital: "Funafuti", cities: ["Alapi", "Senala", "Vaiaku", "Fakaifou", "Teone", "Funafuti"] },
    { name: "Vanuatu", code: "vu", continent: "Oceania", capital: "Port Vila", cities: ["Luganville", "Norsup", "Isangel", "Sola", "Lakatoro", "Port Vila"] }
];

